blank_issues_enabled: true
contact_links:
  - name: Lily Support
    url: https://t.me/Lily_x_bots
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://aelly.tk
    about: Basic documentation for setting up.
